---
- name: reload facts
  setup: filter='*'

- name: Create zabbix agent dir for scripts
  file: path=/etc/zabbix/script/grafana state=directory mode=755 owner=root group=root

- name: Copy redis scripts for monitoring
  copy: src=grafana_zabbix dest=/etc/zabbix/script/grafana/grafana_zabbix mode=755 owner=root group=root

- name: Add crontab to grafana monitoring
  cron: name="Grafana Zabbix sender" minute=*/5 cron_file=zabbix user=zabbix job="/etc/zabbix/script/grafana/grafana_zabbix --zabbix {{ zabbix_server }}"
